version: "3.8"
services:  

  gunicorn1:
    build: ./gunicorn
    networks:
      - forecast-app

  gunicorn2:
    build: ./gunicorn
    networks:
      - forecast-app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - forecast-app
    depends_on:
      - gunicorn1
      - gunicorn2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-certificate.crt:/etc/nginx/certificate/nginx-certificate.crt
      - ./nginx/nginx.key:/etc/nginx/certificate/nginx.key

networks:
  forecast-app:
