pipeline {
    agent {
        label 'production'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }
    stages {
        stage('Take down containers and clean') {
            steps {
                cleanWs()
                sh 'if [[ -n $(docker ps -q) ]]; then docker stop $(docker ps -q); fi'
                sh 'if [[ -n $(docker ps -aq) ]]; then docker rm $(docker ps -aq); fi'
                sh 'docker image prune -f'
                sh 'echo $(docker ps -q)'
            }
        }
        stage('Fetch git repo') {
            steps {
                git credentialsId: '45551286-fc7b-437b-a6e2-f67305b09ff1', url: 'http://172.31.22.73/gitlab-instance-d4e39dbd/forecast_api'
            }
        }
        stage('Pull image from Docker hub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh "docker pull amihaiba/forecast_api:latest"
                sh 'docker pull nginx:alpine'
            }
        }
        stage('Set up containers') {
        	steps {
        	    dir (env.WORKSPACE+'/source-files') {
        	        sh 'docker-compose up -d'
        	    }
        	}
        }
    }
    post {
        success {
            slackSend channel: "#succeeded-build", color: "good", message: "Build amihaiba/forecast_api:latest deployed successfuly!"
        }
        failure {
            slackSend channel: "#devops-alerts", color: "danger", message: "Build amihaiba/forecast_api:latest failed to deploy!"
        }
        always {
            sh 'docker logout'
        }
    }
 }